# Site settings
title: Jiaxi's Blog
email: jiaxiluo@umich.edu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://jiaxiluo.github.io"

# Build settings
markdown: kramdown
permalink: pretty
